#include "rtwtypes.h"
#include "xdlaev2_SAINBEU8.h"
#include "mwmathutil.h"
void xdlaev2_SAINBEU8 ( real_T a_prot , real_T b_prot , real_T c_prot ,
real_T * rt1_prot , real_T * rt2_prot , real_T * cs1_prot , real_T * sn1_prot
) { real_T ab_prot ; real_T acmn_prot ; real_T acmx_prot ; real_T adf_prot ;
real_T b_a_prot ; real_T df_prot ; real_T sm_prot ; real_T tb_prot ; int32_T
sgn1_prot ; int32_T sgn2_prot ; sm_prot = a_prot + c_prot ; df_prot = a_prot
- c_prot ; adf_prot = muDoubleScalarAbs ( df_prot ) ; tb_prot = b_prot +
b_prot ; ab_prot = muDoubleScalarAbs ( tb_prot ) ; if ( muDoubleScalarAbs ( a_prot ) > muDoubleScalarAbs ( c_prot ) ) { acmx_prot = a_prot ; acmn_prot = c_prot ; } else { acmx_prot = c_prot ; acmn_prot = a_prot ; } if ( adf_prot > ab_prot ) { b_a_prot = ab_prot / adf_prot ; adf_prot *= muDoubleScalarSqrt ( b_a_prot * b_a_prot + 1.0 ) ; } else if ( adf_prot < ab_prot ) { adf_prot /= ab_prot ; adf_prot = muDoubleScalarSqrt ( adf_prot * adf_prot + 1.0 ) * ab_prot ; } else { adf_prot = ab_prot * 1.4142135623730951 ; } if ( sm_prot < 0.0 ) { * rt1_prot = ( sm_prot - adf_prot ) * 0.5 ; sgn1_prot = - 1 ; * rt2_prot = acmx_prot / * rt1_prot * acmn_prot - b_prot / * rt1_prot * b_prot ; } else if ( sm_prot > 0.0 ) { * rt1_prot = ( sm_prot + adf_prot ) * 0.5 ; sgn1_prot = 1 ; * rt2_prot = acmx_prot / * rt1_prot * acmn_prot - b_prot / * rt1_prot * b_prot ; } else { * rt1_prot = 0.5 * adf_prot ; * rt2_prot = - 0.5 * adf_prot ; sgn1_prot = 1 ; } if ( df_prot >= 0.0 ) { df_prot += adf_prot ; sgn2_prot = 1 ; } else { df_prot -= adf_prot ; sgn2_prot = - 1 ; } if ( muDoubleScalarAbs ( df_prot ) > ab_prot ) { tb_prot = - tb_prot / df_prot ; * sn1_prot = 1.0 / muDoubleScalarSqrt ( tb_prot * tb_prot + 1.0 ) ; * cs1_prot = tb_prot * * sn1_prot ; } else if ( ab_prot == 0.0 ) { * cs1_prot = 1.0 ; * sn1_prot = 0.0 ; } else { tb_prot = - df_prot / tb_prot ; * cs1_prot = 1.0 / muDoubleScalarSqrt ( tb_prot * tb_prot + 1.0 ) ; * sn1_prot = tb_prot * * cs1_prot ; } if ( sgn1_prot == sgn2_prot ) { tb_prot = * cs1_prot ; * cs1_prot = - * sn1_prot ; * sn1_prot = tb_prot ; } }
